CREATE TABLE tracks
(
  kind text,
  id integer not null
    constraint tracks_pk
      primary key,
  created_at text,
  user_id int,
  duration int,
  commentable boolean,
  state text,
  originalsize int,
  lastmodified text,
  sharing text,
  teglist text,
  permalink text,
  "streamable " boolean,
  embeddableby text,
  purchasetitle text,
  labelID int,
  genre text,
  title text,
  description text,
  labelname text,
  releasetrack text,
  tracktype text,
  key_signature text,
  isrc text,
  videourl text,
  bpm float,
  release_year int,
  release_month int,
  release_day int,
  original_format text,
  license text,
  uri text,
  creator text,
  permalinkurl text,
  artworkurl text,
  streamurl text,
  downloadurl text,
  playback int,
  downloads int,
  favoritings int,
  reposts int,
  comments int,
  downloadable boolean,
  waveform text,
  attachmentsURI text,
  Policy text,
  monetization text
);

CREATE TABLE users
(
  id integer not null
    constraint users_pk
      primary key,
  kind text,
  permalinl text,
  username text,
  last_modified text,
  uri text,
  permurl text,
  avatar text,
  country text,
  first_name text,
  last_name text,
  full_name text,
  "description " text,
  city text,
  discogs_name text,
  myspace text,
  website text,
  website_title text,
  tracks int,
  playlists int,
  plan_ text,
  public_favorites int,
  followers int,
  followings int,
  subscriptions text,
  likes int,
  reposts int,
  comments int
);